# Generated by Django 5.1.7 on 2025-04-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_alter_attendance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
