# Generated by Django 5.1.7 on 2025-04-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_alter_attendance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="dummy",
            field=models.BooleanField(default=False),
        ),
    ]
