# Generated by Django 5.1.7 on 2025-03-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(default="0000000000", max_length=15),
            preserve_default=False,
        ),
    ]
