# Generated by Django 5.1.7 on 2025-04-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_subject_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="timestamp",
            field=models.DateTimeField(db_index=True),
        ),
    ]
