# Generated by Django 5.1.7 on 2025-04-28 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_attendance_dummy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="dummy",
        ),
    ]
