# Generated by Django 5.1.7 on 2025-04-30 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_remove_attendance_dummy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["session", "student", "status", "timestamp"],
                name="app_attenda_session_f28ac5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(fields=["name"], name="app_program_name_3894eb_idx"),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["program", "year", "name"],
                name="app_section_program_c69638_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["timetable", "date", "status"],
                name="app_session_timetab_3c60ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["roll_number", "email", "section", "semester"],
                name="app_student_roll_nu_e9d941_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["semester", "is_law_subject"],
                name="app_subject_semeste_668e2b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(fields=["email"], name="app_teacher_email_aad138_idx"),
        ),
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(
                fields=["section", "subject", "teacher"],
                name="app_timetab_section_f8fd94_idx",
            ),
        ),
    ]
