# Generated by Django 5.1.7 on 2025-03-23 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="pass_field",
        ),
    ]
