# Generated by Django 5.1.7 on 2025-03-23 08:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance_app", "0005_alter_teacher_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="user",
        ),
    ]
