# Generated by Django 5.1.7 on 2025-08-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_email_alter_student_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll_number'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(choices=[('08:30:00', '08:30 AM - 09:30 AM'), ('09:30:00', '09:30 AM - 10:30 AM'), ('10:30:00', '10:30 AM - 11:30 AM'), ('12:00:00', '12:00 PM - 01:00 PM'), ('01:00:00', '01:00 PM - 02:00 PM')]),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['roll_number'], name='app_student_roll_nu_319056_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['first_name', 'last_name'], name='app_student_first_n_de9b19_idx'),
        ),
    ]
