# Generated by Django 5.1.7 on 2025-12-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_options_alter_timetable_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(choices=[('08:00:00', '08:00 AM - 09:00 AM'), ('08:30:00', '08:30 AM - 09:30 AM'), ('09:00:00', '09:00 AM - 10:00 AM'), ('09:30:00', '09:30 AM - 10:30 AM'), ('10:00:00', '10:00 AM - 11:00 AM'), ('10:30:00', '10:30 AM - 11:30 AM'), ('11:00:00', '11:00 AM - 12:00 AM'), ('11:30:00', '11:30 AM - 12:30 AM'), ('12:00:00', '12:00 PM - 01:00 PM'), ('12:30:00', '12:30 PM - 01:30 PM'), ('01:00:00', '01:00 PM - 02:00 PM'), ('01:30:00', '01:30 PM - 02:30 PM'), ('02:00:00', '02:00 PM - 03:00 PM')]),
        ),
    ]
