# Generated by Django 5.1.7 on 2025-12-31 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
