# Generated by Django 5.1.7 on 2025-12-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='session_date',
            field=models.DateField(),
        ),
    ]
