# Generated by Django 5.1.7 on 2025-12-31 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_attendance_session_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance'},
        ),
        migrations.AddField(
            model_name='attendance',
            name='semester',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_roll_number',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='archived_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='archived_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='app.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app.section'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['session_date', 'student_roll_number'], name='app_attenda_session_bf2e82_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['section_name', 'session_date'], name='app_attenda_section_cfd4b0_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active'], name='app_student_is_acti_ffdc21_idx'),
        ),
    ]
