# Generated by Django 5.1.7 on 2025-12-31 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_attendance_options_attendance_semester_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='app_attenda_session_bf2e82_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='app_attenda_section_cfd4b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='app_student_is_acti_ffdc21_idx',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='archived_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='archived_reason',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_roll_number',
            field=models.CharField(db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.section'),
        ),
    ]
