# Generated by Django 5.1.7 on 2026-01-01 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivalAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_roll_number', models.CharField(db_index=True, max_length=20)),
                ('student_name', models.CharField(max_length=150)),
                ('section_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('session_date', models.DateField(db_index=True)),
                ('semester', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('original_timestamp', models.DateTimeField()),
                ('original_recorded_by', models.CharField(max_length=200)),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('archive_note', models.TextField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_records', to='app.teacher')),
            ],
            options={
                'verbose_name': 'Archival Attendance',
                'verbose_name_plural': 'Archival Attendance Records',
                'ordering': ['-archived_at', '-session_date'],
                'indexes': [
                    models.Index(fields=['student_roll_number', 'session_date'], name='app_archiva_student_4c6f5c_idx'),
                    models.Index(fields=['archived_at'], name='app_archiva_archive_e8d2a3_idx'),
                ],
            },
        ),
    ]
