# Generated by Django 5.1.7 on 2026-01-07 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_add_archival_attendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Present", "Present"),
                            ("Absent", "Absent"),
                            ("On Leave", "On Leave"),
                        ],
                        default="Absent",
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Teacher Attendance",
                "verbose_name_plural": "Teacher Attendance",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterModelOptions(
            name="attendance",
            options={"verbose_name": "Attendance", "verbose_name_plural": "Attendance"},
        ),
        migrations.RenameIndex(
            model_name="archivalattendance",
            new_name="app_archiva_student_631421_idx",
            old_name="app_archiva_student_4c6f5c_idx",
        ),
        migrations.RenameIndex(
            model_name="archivalattendance",
            new_name="app_archiva_archive_1809b3_idx",
            old_name="app_archiva_archive_e8d2a3_idx",
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "session")},
        ),
        migrations.RemoveField(
            model_name="student",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="app.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance",
                to="app.session",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance",
                to="app.student",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="timestamp",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddField(
            model_name="teacherattendance",
            name="marked_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_teacher_attendance",
                to="app.teacher",
            ),
        ),
        migrations.AddField(
            model_name="teacherattendance",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_attendance",
                to="app.session",
            ),
        ),
        migrations.AddField(
            model_name="teacherattendance",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_attendance",
                to="app.teacher",
            ),
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="section_name",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="session_date",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="student_name",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="student_roll_number",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="subject_name",
        ),
        migrations.AlterUniqueTogether(
            name="teacherattendance",
            unique_together={("teacher", "session")},
        ),
    ]
