# Generated by Django 5.1.7 on 2026-07-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_teacherattendance_alter_attendance_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeacherAttendance",
        ),
    ]
