# Generated by Django 5.1.7 on 2025-03-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_student_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
    ]
