# Generated by Django 5.1.7 on 2025-03-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_student_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("name", "semester")},
        ),
    ]
