# Generated by Django 5.1.7 on 2025-03-28 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_subject_name_alter_subject_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetable",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timetable",
                to="app.teacher",
            ),
        ),
    ]
