# Generated by Django 5.1.7 on 2025-04-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_teacher_is_admin_alter_teacher_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
