# Generated by Django 5.1.7 on 2025-04-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_attendance_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="semester",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
