# Generated by Django 5.1.7 on 2025-04-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_student_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="semester",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
