# Generated by Django 5.1.7 on 2025-04-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_student_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="roll_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
