# Generated by Django 5.1.7 on 2025-04-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_alter_attendance_status_alter_attendance_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[("Present", "Present"), ("Absent", "Absent")],
                default="Absent",
                max_length=7,
            ),
        ),
    ]
